### ISSUE TITLE
React Project Setup using Create React App

### ISSUE THREAD

**Issue by mickeymond** [mickeymond/ecommerce-app-alpha#1]
https://create-react-app.dev/

1. Create the React app
2. Ensure the default branch is main
3. Push  your local main to origin main

**Comment by teyvi** [comment]
@Hannan-Laaraba its been more than 10 minutes 🙃

**Comment by Hannan-Laaraba** [comment]
@teyvi patience is a virtue

**Comment by mickeymond** [comment]
@Hannan-Laaraba I prefer to not have lock files in repos.
Can we remove the package-lock.json file and add the following lines of code to the .gitignore file?

```
package-lock.json
yarn.lock
```
